### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9268, 9061, 3186, 5324], [9268, 9061, 3186, 6846], [9268, 5078, 3186, 3023], [6010, 998, 7125, 8621, 6668], [6010, 998, 7125, 8621, 4186], [3686, 9268, 8849, 3186, 5106], [9519, 4679, 6089, 8621]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9268 9061 3186 5324]
 [   0    0    0    0 9268 9061 3186 6846]
 [   0    0    0    0 9268 5078 3186 3023]
 [   0    0    0 6010  998 7125 8621 6668]
 [   0    0    0 6010  998 7125 8621 4186]
 [   0    0    0 3686 9268 8849 3186 5106]
 [   0    0    0    0 9519 4679 6089 8621]]


In [10]:
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.02701392  0.03953112 -0.02501205 -0.03888067 -0.02826127
   -0.01133274 -0.02649492  0.02477005  0.01781677  0.02279525]
  [-0.02701392  0.03953112 -0.02501205 -0.03888067 -0.02826127
   -0.01133274 -0.02649492  0.02477005  0.01781677  0.02279525]
  [-0.02701392  0.03953112 -0.02501205 -0.03888067 -0.02826127
   -0.01133274 -0.02649492  0.02477005  0.01781677  0.02279525]
  [-0.02701392  0.03953112 -0.02501205 -0.03888067 -0.02826127
   -0.01133274 -0.02649492  0.02477005  0.01781677  0.02279525]
  [ 0.02706743  0.03180395 -0.03439814 -0.02582737  0.04525551
    0.01481015  0.04766115 -0.00437639  0.04886555 -0.0239303 ]
  [-0.0317947  -0.01358596  0.04299283  0.0314577  -0.04751642
   -0.02904717 -0.01244562 -0.02355483 -0.01021878 -0.03291224]
  [-0.01309073 -0.03382461  0.01216134  0.03539438  0.04476288
   -0.02638407  0.03473376  0.02846009 -0.00507694  0.04392678]
  [ 0.00893323 -0.02905146  0.00863779 -0.03735368 -0.01453282
    0.01303761 -0.00335823 -0.02773718  0.035045

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9268, 9061, 3186, 5324])

In [15]:
print(model.predict(embedded_docs)[0])

[[-0.02701392  0.03953112 -0.02501205 -0.03888067 -0.02826127 -0.01133274
  -0.02649492  0.02477005  0.01781677  0.02279525]
 [-0.02701392  0.03953112 -0.02501205 -0.03888067 -0.02826127 -0.01133274
  -0.02649492  0.02477005  0.01781677  0.02279525]
 [-0.02701392  0.03953112 -0.02501205 -0.03888067 -0.02826127 -0.01133274
  -0.02649492  0.02477005  0.01781677  0.02279525]
 [-0.02701392  0.03953112 -0.02501205 -0.03888067 -0.02826127 -0.01133274
  -0.02649492  0.02477005  0.01781677  0.02279525]
 [ 0.02706743  0.03180395 -0.03439814 -0.02582737  0.04525551  0.01481015
   0.04766115 -0.00437639  0.04886555 -0.0239303 ]
 [-0.0317947  -0.01358596  0.04299283  0.0314577  -0.04751642 -0.02904717
  -0.01244562 -0.02355483 -0.01021878 -0.03291224]
 [-0.01309073 -0.03382461  0.01216134  0.03539438  0.04476288 -0.02638407
   0.03473376  0.02846009 -0.00507694  0.04392678]
 [ 0.00893323 -0.02905146  0.00863779 -0.03735368 -0.01453282  0.01303761
  -0.00335823 -0.02773718  0.03504565 -0.04996613]]